# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Joke.create(content: "I'm reading a book about anti-gravity. I can't put it down.")
Joke.create(content: "A burger walks into a bar. The bartender says 'Sorry, we don't serve food here'")
Joke.create(content: "I was up all night wondering where the sun went, but then it dawned on me.")

Tag.create(name: " Airplane Joke")
Tag.create(name: " Animal Joke")
Tag.create(name: " Baby Joke")
Tag.create(name: " Bar & Drinking Joke")
Tag.create(name: " Business Joke")
Tag.create(name: " College Joke")
Tag.create(name: " Computer Joke")
Tag.create(name: " Cross the Road Joke")
Tag.create(name: " Dentist Joke")
Tag.create(name: " Doctor Joke")
Tag.create(name: " Dumb Criminals")
Tag.create(name: " Elderly Joke")
Tag.create(name: " Entertainment Joke")
Tag.create(name: " Family Joke")
Tag.create(name: " Farmer Joke")
Tag.create(name: " Food Joke")
Tag.create(name: " Golf Joke")
Tag.create(name: " Holiday Joke")
Tag.create(name: " Judge Joke")
Tag.create(name: " Kid Joke")
Tag.create(name: " Knock-Knock Joke")
Tag.create(name: " Lawyer Joke")
Tag.create(name: " Lightbuld Joke")
Tag.create(name: " Little Johnny Joke")
Tag.create(name: " Love Joke")
Tag.create(name: " Marriage Joke")
Tag.create(name: " Military Joke")
Tag.create(name: " Misc Joke")
Tag.create(name: " Money Joke")
Tag.create(name: " Musician Joke")
Tag.create(name: " National Joke")
Tag.create(name: " News Joke")
Tag.create(name: " Office Joke")
Tag.create(name: " One-Liner Joke")
Tag.create(name: " Pickup Joke")
Tag.create(name: " Police Joke")
Tag.create(name: " Political Joke")
Tag.create(name: " Pop Culture Joke")
Tag.create(name: " Programmer Joke")
Tag.create(name: " Puns")
Tag.create(name: " Relationship Joke")
Tag.create(name: " Religious Joke")
Tag.create(name: " Salepeople Joke")
Tag.create(name: " School Joke")
Tag.create(name: " Science Joke")
Tag.create(name: " Scifi Joke")
Tag.create(name: " Sport Joke")
Tag.create(name: " Star Wars Joke")
Tag.create(name: " Teacher Joke")
Tag.create(name: " Technology Joke")
Tag.create(name: " Word Play Joke")
Tag.create(name: " Work Joke")
Tag.create(name: " Yo Mama Joke")